apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jontasreis/transfer-bank-backend
          envFrom:
            - secretRef:
                name: backend
          ports:
            - containerPort: 3000
