apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  KAFKA_HOST: cGtjLTZvanYyLnVzLXdlc3Q0LmdjcC5jb25mbHVlbnQuY2xvdWQ6OTA5Mg==
  KAFKA_CLIENT_ID: YmFja2VuZA==
  KAFKA_SASL_USERNAME: Wkk2SUpHRjNMSVpQSEFXSw==
  KAFKA_SASL_PASSWORD: YnM4WXRhcXR5WC8wc0NHQ3Jxb2IvcEc4VmpURmI2MjBhODdyc0RaZlM4R3JSUjRLZndOZm85anRKK2hUTVZDTw==
  KAFKA_USE_SSL: dHJ1ZQ==
  DB_CONNECTION: bXlzcWw=
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: Tzd5RzVJQVMxdQ==
  DB_HOST: bXlzcWw=
  DB_DATABASE: YmFja2VuZA==
  DB_PORT: MzMwNg==
